CREATE TABLESPACE TS_ILE_DATOS
DATAFILE 'ts_ile_datos01.dbf'
SIZE 500M
AUTOEXTEND ON
NEXT 50M
MAXSIZE 2G;

CREATE TABLESPACE TS_ILE_INDICES
DATAFILE 'ts_ile_indices01.dbf'
SIZE 200M
AUTOEXTEND ON
NEXT 20M
MAXSIZE 1G;

CREATE TEMPORARY TABLESPACE TS_ILE_TEMP
TEMPFILE 'ts_ile_temp01.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 500M;

